---
title: "Tooltips"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

### [Tippy](http://tippy.john-coene.com/) tooltips

Install the development version of tippy from GitHub. You can also get it from
CRAN, but the CRAN version (0.0.1) isn't keyboard accessible.
```{r, eval=FALSE}
# install.packages("remotes")
remotes::install_github("JohnCoene/tippy")
```

```{r}
library(reactable)
library(htmltools)
library(tippy)

with_tooltip <- function(value, tooltip, ...) {
  content <- tippy(value, tooltip, ...)
  div(style = "text-decoration: underline; text-decoration-style: dotted;", content)
}

reactable(
  mtcars[, 1:6],
  columns = list(
    mpg = colDef(header = function(value) {
      with_tooltip(value, "Miles/gallon")
    }),
    cyl = colDef(header = function(value) {
      with_tooltip(value, "Number of cylinders")
    }),
    disp = colDef(header = function(value) {
      with_tooltip(value, "Displacement (cu.in.)")
    }),
    .rownames = colDef(cell = function(value) {
      if (value == "Mazda RX4 Wag") {
        with_tooltip(value, "Mazda RX4 Wagon")
      } else {
        value
      }
    })
  )
)
```

```{css echo=FALSE}
/* rmarkdown html documents */
.main-container {
  font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Helvetica, Arial, sans-serif;
}

.main-container blockquote {
  font-size: inherit;
}

/* pkgdown articles */
.contents {
  font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Helvetica, Arial, sans-serif;
}

.contents blockquote {
  font-size: inherit;
}

.reactable {
  font-size: 14px;
}
```
