---
title: "Row Details"
output:
  html_document:
    css: assets/styles.css
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

### Render function in R

```{r}
library(reactable)

reactable(iris, details = rowDetails(
  function(index) {
    htmltools::div(
      htmltools::h4(paste("Details for row:", index)),
      reactable(iris[index, ], inline = TRUE, outlined = TRUE)
    )
  }
))
```

### Render function in JS

```{r}
reactable(iris, details = rowDetails(
  JS("
    function(rowInfo) {
      return '<h4>Details for row: ' + rowInfo.index + '</h4>' +
        '<pre>' + JSON.stringify(rowInfo, null, 2) + '</pre>'
    }
  "),
  html = TRUE,
  name = "More",
  width = 50
))
```

### Subtables

> NOTE: only supported by R render functions

```{r}
by_species <- aggregate(iris[, 1:4], by = list(Species = iris$Species), FUN = mean)

reactable(by_species, details = rowDetails(
  function(index) {
    species <- by_species[index, "Species"]
    htmltools::div(
      htmltools::h4(paste("Species:", species)),
      reactable(iris[iris$Species == species, ], details = rowDetails(
        JS("function(rowInfo) { return 'Species: ' + rowInfo.row.Species }")
      ))
    )
  }
))
```

### Conditional row details

> NOTE: only supported by R render functions

```{r}
reactable(iris, details = rowDetails(
  function(index) {
    if (index %in% c(3, 5)) {
      reactable(data.frame(x = c(1, 2, 3), y = c("a", "b", "c")), inline = TRUE)
    }
  }
))
```
