---
title: "Sorting"
output:
  html_document:
    css: assets/styles.css
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

### Default sorting

```{r}
library(reactable)

reactable(
  iris,
  defaultSortOrder = "desc",
  defaultSorted = list(Sepal.Length = "asc", Petal.Length = "desc"),
  columns = list(
    Species = colDef(defaultSortOrder = "asc")
  )
)
```

*NOTE: shift+click to sort multiple columns*

### NA and Infinity handling

```{r}
reactable(
  data.frame(
    n = seq(7),
    x = c(5, 7, NA, NaN, 9, 0, -20),
    y = c(1, NA, NA, -Inf, 0, Inf, -5)
  ),
  columns = list(
    x = colDef(showNA = TRUE)
  )
)
```

### Sort NAs to the bottom

```{r}
reactable(
  data.frame(
    n = c(1, 2, 3, 4, 5),
    x = c(2, 3, 1, NA, NA),
    y = c(4, 5, 6, NA, NA)
  ),
  defaultColDef = colDef(sortMethod = "naLast"),
  defaultSorted = "x"
)
```

### Show sortable columns

```{r}
reactable(iris, sortable = FALSE, showSortable = TRUE, columns = list(
  Petal.Width = colDef(sortable = TRUE),
  Petal.Length = colDef(sortable = TRUE)
))
```
